### ISSUE TITLE
unparseable undefined tag

### ISSUE THREAD

**Issue by WendelHime** [dsoprea/go-exif#47] opened 2020-11-04 15:33 UTC
I'm trying to write metadata on this image (I hope github don't make changes on metadata, if it does, I'll provide another link):

![IMG_20201102_110021](https://user-images.githubusercontent.com/6754291/98129047-6cd93000-1e97-11eb-9a21-d2530dcc436a.jpg)

That's the original picture that I take from Ada with my phone. I'm using this code based on [example](https://pkg.go.dev/github.com/dsoprea/go-jpeg-image-structure/v2#example-SegmentList.SetExif)

```go
	jmp := jpg.NewJpegMediaParser()

	intfc, err := jmp.ParseBytes(b.Bytes())
	if err != nil {
		return err
	}

	sl := intfc.(*jpg.SegmentList)
	// Update the UserComment tag.
	rootIb, err := sl.ConstructExifBuilder()
	if err != nil {
		return err
	}
```

But when trying to call `exif.ConstructExifBuilder`, the function returns the error: `unparseable undefined tag`.

Somebody help me!

Here's some metadata using [exiftool](https://exiftool.org/) with the command: 
```bash
exiftool -a -u -g1 IMG_20201102_110021.jpg
```
Output:
```
---- ExifTool ----
ExifTool Version Number         : 12.09
Warning                         : [minor] Unrecognized MakerNotes
Warning                         : [minor] Unrecognized MakerNotes
---- System ----
File Name                       : IMG_20201102_110021.jpg
Directory                       : ..
File Size                       : 3.1 MB
File Modification Date/Time     : 2020:11:04 11:11:19-03:00
File Access Date/Time           : 2020:11:04 11:11:31-03:00
File Inode Change Date/Time     : 2020:11:04 11:11:19-03:00
File Permissions                : rw-rw-r--
---- File ----
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Big-endian (Motorola, MM)
Image Width                     : 3456
Image Height                    : 4608
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
---- IFD0 ----
Image Width                     : 3456
Image Height                    : 4608
Bits Per Sample                 : 8 8 8
Image Description               : sdr
Make                            : HUAWEI
Camera Model Name               : BND-L34
Orientation                     : Unknown (0)
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Software                        : BND-L34 8.0.0.362(C567)
Modify Date                     : 2020:11:02 11:00:23
Y Cb Cr Positioning             : Centered
Device Setting Description      : (Binary data 4 bytes, use -b option to extract)
---- ExifIFD ----
Document Name                   : 
Exposure Time                   : 1/256
F Number                        : 2.2
Exposure Program                : Program AE
ISO                             : 50
Exif Version                    : 0210
Date/Time Original              : 2020:11:02 11:00:23
Create Date                     : 2020:11:02 11:00:23
Components Configuration        : Y, Cb, Cr, -
Shutter Speed Value             : 1/999963365
Aperture Value                  : 2.2
Brightness Value                : 0
Exposure Compensation           : 0
Metering Mode                   : Multi-segment
Light Source                    : Daylight
Flash                           : No Flash
Focal Length                    : 3.8 mm
Maker Note Unknown Text         : Auto
Sub Sec Time                    : 543266
Sub Sec Time Original           : 543266
Sub Sec Time Digitized          : 543266
Flashpix Version                : 0100
Color Space                     : sRGB
Exif Image Width                : 3456
Exif Image Height               : 4608
Sensing Method                  : One-chip color area
File Source                     : Digital Camera
Scene Type                      : Directly photographed
Custom Rendered                 : Custom
Exposure Mode                   : Auto
White Balance                   : Auto
Digital Zoom Ratio              : 1
Focal Length In 35mm Format     : 26 mm
Scene Capture Type              : Standard
Gain Control                    : None
Contrast                        : Normal
Saturation                      : Normal
Sharpness                       : Normal
Subject Distance Range          : Unknown
---- InteropIFD ----
Interoperability Index          : R98 - DCF basic file (sRGB)
Interoperability Version        : 0100
---- IFD1 ----
Image Width                     : 384
Image Height                    : 512
Compression                     : JPEG (old-style)
Orientation                     : Unknown (0)
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Thumbnail Offset                : 8592
Thumbnail Length                : 19480
Thumbnail Image                 : (Binary data 19480 bytes, use -b option to extract)
---- JFIF ----
JFIF Version                    : 1.01
Resolution Unit                 : inches
X Resolution                    : 96
Y Resolution                    : 96
---- Composite ----
Aperture                        : 2.2
Image Size                      : 3456x4608
Megapixels                      : 15.9
Scale Factor To 35 mm Equivalent: 6.8
Shutter Speed                   : 1/256
Create Date                     : 2020:11:02 11:00:23.543266
Date/Time Original              : 2020:11:02 11:00:23.543266
Modify Date                     : 2020:11:02 11:00:23.543266
Circle Of Confusion             : 0.004 mm
Field Of View                   : 69.4 deg
Focal Length                    : 3.8 mm (35 mm equivalent: 26.0 mm)
Hyperfocal Distance             : 1.51 m
Light Value                     : 11.3
```

**Comment by dsoprea** [comment] 2020-11-06 17:22
There are potentially manufacturer-specific tags of type "undefined" in images that typically have a proprietary format to that manufacturer/brand. Most of these are unhandled. Failing on them is technically not a bug, though there should be a way to ignore them (so that the user knows that there will be some data-loss, even if the user doesn't necessarily care about it).

We can look at taking care of this next week.

**Comment by dsoprea** [comment] 2020-11-27 04:22
I'm unable to reproduce with the picture above. You didn't include a stacktrace and you didn't include a revision (I don't know if you're using the latest version of the v3 release, or something older). Can you respond with both, and try with latest v3 if you're not already?

**Comment by dsoprea** [comment] 2020-11-27 04:23
You can also attach the image to an email sent to dustin@randomingenuity.com, just to make sure that it wasn't modified by embedding.

**Comment by dsoprea** [comment] 2020-11-29 05:35
Let me know if you want to move forward with this. Closing for now.

**Closed by dsoprea** 2020-11-29 05:35 UTC
